# Generated by Django 3.0.3 on 2020-03-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200315_0851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='users',
            new_name='user',
        ),
    ]
